EternalKingdom/src/Entity/Lord.php
<?php

namespace App\Entity;

use App\Entity\World\WorldMapNode;
use App\Enum\TitleType;
use App\Enum\HealthType;
use App\Repository\LordRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * Lord is a character that is playing a game.
 * If a player has no lord, he doesn't play any game.
 *
 * @ORM\Entity(repositoryClass=LordRepository::class)
 */
class Lord
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     */
    private $ageYear = 20;

    /**
     * @ORM\Column(type="float")
     */
    private $ageMonth = 0;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $health = HealthType::TYPE_EXCELLENT;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $title = TitleType::TYPE_KNIGHT;

    /**
     * @ORM\Column(type="integer")
     */
    private $glory = 1;

    /**
     * @ORM\Column(type="integer")
     */
    private $maxGlory = 1;

    /**
     * @ORM\OneToOne(targetEntity=City::class, mappedBy="lord", cascade={"persist", "remove"})
     */
    private $city;

    /**
     * @ORM\OneToMany(targetEntity=General::class, mappedBy="owner", cascade={"persist", "remove"})
     */
    private $generals;

    /**
     * @ORM\OneToMany(targetEntity=WorldMapNode::class, cascade={"persist", "remove"}, mappedBy="owner")
     */
    private $kingdom;

    public function __construct()
    {
        $this->generals = new ArrayCollection();
        $this->kingdom = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getAgeYear(): ?int
    {
        return $this->ageYear;
    }

    public function setAgeYear(int $ageYear): self
    {
        $this->ageYear = $ageYear;

        return $this;
    }

    public function getAgeMonth(): ?float
    {
        return $this->ageMonth;
    }

    public function setAgeMonth(float $ageMonth): self
    {
        $this->ageMonth = $ageMonth;

        return $this;
    }

    public function getHealth(): ?string
    {
        return $this->health;
    }

    public function setHealth(string $health): self
    {
        if(!in_array($health, HealthType::getAvailableTypes()))
        {
            throw new InvalidArgumentException("Invalid type");
        }
        $this->health = $health;
        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        if(!in_array($title, TitleType::getAvailableTypes()))
        {
            throw new InvalidArgumentException("Invalid type");
        }
        $this->title = $title;
        return $this;
    }

    public function getGlory(): ?int
    {
        return $this->glory;
    }

    public function setGlory(int $glory): self
    {
        $this->glory = $glory;

        return $this;
    }

    public function getMaxGlory(): ?int
    {
        return $this->maxGlory;
    }

    public function setMaxGlory(int $maxGlory): self
    {
        $this->maxGlory = $maxGlory;

        return $this;
    }

    public function getCity(): ?City
    {
        return $this->city;
    }

    public function &getCityRef() : ?City
    {
        return $this->city;
    }

    public function setCity(City $city): self
    {
        // set the owning side of the relation if necessary
        if ($city->getLord() !== $this) {
            $city->setLord($this);
        }

        $this->city = $city;

        return $this;
    }

    /**
     * @return Collection|General[]
     */
    public function getGenerals(): Collection
    {
        return $this->generals;
    }

    /**
     * @return int
     */
    public function getGeneralCount(): int
    {
        return count($this->generals);
    }

    public function addGeneral(General $general): self
    {
        if (!$this->generals->contains($general)) {
            $this->generals[] = $general;
            $general->setOwner($this);
        }

        return $this;
    }

    public function removeGeneral(General $general): self
    {
        if ($this->generals->removeElement($general)) {
            // set the owning side to null (unless already changed)
            if ($general->getOwner() === $this) {
                $general->setOwner(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|WorldMapNode[]
     */
    public function getKingdom(): Collection
    {
        return $this->kingdom;
    }

    public function addTerritory(WorldMapNode $kingdom): self
    {
        if (!$this->kingdom->contains($kingdom)) {
            $this->kingdom[] = $kingdom;
            $kingdom->setOwner($this);
        }

        return $this;
    }

    public function removeTerritory(WorldMapNode $kingdom): self
    {
        if ($this->kingdom->removeElement($kingdom)) {
            // set the owning side to null (unless already changed)
            if ($kingdom->getOwner() === $this) {
                $kingdom->setOwner(null);
            }
        }

        return $this;
    }

    public function getTrade(): int
    {
        $total = 0;
        foreach($this->kingdom as $node)
        {
            $total += $node->getTrade();
        }
        return $total;
    }

    public function getReputation(): int
    {
        $total = 0;
        foreach($this->generals as $general)
        {
            $total += $general->getReputation();
        }
        return $total;
    }

    public function isAlive(): bool
    {
        return $this->health != HealthType::TYPE_DEAD;
    }
}

EternalKingdom/src/Controller/ManagementController.php
<?php

// src/Controller/ManagementController.php
namespace App\Controller;

use App\Entity\Lord;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * ManagementController will display the Management page
 * Inspect how you are, your cities, your relations with other realms, your productions, ...
 * @package App\Controller
 */
class ManagementController extends AbstractController
{
    /**
     * Lord Management page
     * Forwarded from DefaultController when accessing index webpage.
     * @Route("/management/{id}")
     *
     * @param int $id LordId
     * @return Response
     */
    public function Management(int $id): Response
    {
        $lordRepository = $lord = $this->GetDoctrine()->GetRepository(Lord::class);
        $lord = $lordRepository->find($id);

        return $this->render(
            'Management/management.html.twig',
            [
                'lord' => $lord
            ]
        );
    }
}

EternalKingdom/templates/Management/Components/DiplomacyTab.html.twig
<div id="diplomacy" style="display : none">
                                <p class="nothing">
                                    {{ 'tabs.diplomacy.noDiplomacy' | trans([], 'Management') }}
                                </p>

                                <a href="http://kingdom.muxxu.com/?tab=diplo;dinv=1" class="button"
                                   onmouseover="mt.js.Tip.show(this,'&lt;div class=\'tiptop\'&gt;&lt;div class=\'tipbottom\'&gt;&lt;div class=\'tipbg\'&gt;Voir les accords diplomatiques des autres joueurs vous concernant&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;')"
                                   onmouseout="mt.js.Tip.hide()">Inverser</a>

                                <p>
                                    Chercher un joueur :
                                </p>

                                <form action="http://kingdom.muxxu.com/search" method="POST"
                                      class="searchpla">
                                    <div class="tid_userSearchContainer"
                                         style="width: 145px; height: 36px; float: left;"><img
                                                class="tid_loadingSearch"
                                                src="{{ asset('img/loading.gif') }}">
                                        <div class="tid_search_popup"
                                             style="display: none; margin-left: 25px;"></div>
                                        <div class="tid_search_popup" style="display:none"></div>
                                        <a href="http://kingdom.muxxu.com/#"
                                           class="tid_friendsButton"
                                           style="height: 36px; padding-top: 1px; line-height: 36px; z-index: 2; position: absolute;"><img
                                                    class="tid_down"
                                                    src="{{ asset('img/design/arrowDrop.png')}}"
                                                    alt=""><img class="tid_ficon"
                                                                src="{{ asset('img/icons/contact.png')}}"
                                                                alt=""></a><input name="name_name"
                                                                                  class="tid_userSearch inputtext tid_parsed tid_withFriends"
                                                                                  autocomplete="off"
                                                                                  style="width: 116px; height: 36px; float: none; position: absolute; z-index: 1; padding-left: 29px;"><input
                                                type="hidden" name="name" id="undefined"></div>
                                    <input type="submit" value="Chercher" class="button">
                                </form>

                            </div>

EternalKingdom/templates/Management/Components/GeneralsTab.html.twig
<div id="generals" style="display: none;">
    {% if (lord.generals|length) == 0 %}
        <p class="nothing">
            {{ 'tabs.generals.noGeneral' | trans([], 'Management') }}
        </p>
    {% else %}
        <table class="blocks">
            <tbody>
            <tr>
                {% set a = 0 %}
                {% for general in lord.generals %}  
                    {% if a%3 == 0 %}
                    </tr> <tr>
                    {% endif %}
                    {% set a = a+1 %}
                    <td>
                        <div class="blocks_top">
                            <h3 class="h3c">
                                <p class="gdef">
                                    <a href="/map?id={{ app.request.get('id') }}">{{ general.name }}</a>
                                </p>
                            </h3>
                            <div class="blocks_bg">
                                <div class="blocks_bottom">
                                    <div class="p">
                                        {{ ('tabs.generals.waitingAt') | trans([], 'Management') }} <a href="/map?id={{ app.request.get('id') }}">{{ general.location.name }}</a>
                                    </div>
                                    <p>
                                        <img src="{{ asset('img/help.gif') }}"
                                            class="help"
                                            onmouseover="mt.js.Tip.show(this,'&lt;div class=\'tiptop\'&gt;&lt;div class=\'tipbottom\'&gt;&lt;div class=\'tipbg\'&gt;&lt;h1&gt;{{ 'tabs.generals.reputation' | trans([], 'Management') }}&lt;/h1&gt;{{ 'tabs.generals.reputationTooltip' | trans([], 'Management') }}&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;')"
                                            onmouseout="mt.js.Tip.hide()">
                                        <span class="dt">{{ 'tabs.generals.reputation' | trans([], 'Management') }}</span> :
                                            <strong>{{ general.reputation }}</strong> 
                                        <img src="{{ asset('img/icons/l_rep.png') }}">
                                    </p>
                                    <p>
                                        <img src="{{ asset('img/help.gif') }}"
                                            class="help"
                                            onmouseover="mt.js.Tip.show(this,'&lt;div class=\'tiptop\'&gt;&lt;div class=\'tipbottom\'&gt;&lt;div class=\'tipbg\'&gt;&lt;h1&gt;{{ 'tabs.generals.maintenance' | trans([], 'Management') }}&lt;/h1&gt;{{ 'tabs.generals.maintenanceTooltip' | trans([], 'Management') }}&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;')"
                                            onmouseout="mt.js.Tip.hide()">
                                        <span class="dt">{{ 'tabs.generals.maintenance' | trans([], 'Management') }}</span> :
                                            <strong>{{ max(0, general.armyContainer.TotalUnitCount - general.reputation) }}</strong> 
                                            <img src="{{ asset('img/icons/small/res_gold.gif') }}">
                                    </p>

                                    <ul class="ismall">
                                        {% for army in general.armyContainer.unitArmies %}
                                            {% set unitName = army.resource.name %}
                                            <li>
                                                <div class=""
                                                    onmouseover="mt.js.Tip.show(this,'&lt;div class=\'tiptop\'&gt;&lt;div class=\'tipbottom\'&gt;&lt;div class=\'tipbg\'&gt;&lt;h1&gt;{{ ('units.'~unitName~'.name') | trans([], 'Common') }}&lt;/h1&gt;{{ ('units.'~unitName~'.desc') | trans([], 'Common') }}&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;')"
                                                    onmouseout="mt.js.Tip.hide()">
                                                    <img src="{{ asset('img/icons/small/u_'~army.resource.name~'.gif') }}" alt="">
                                                    <span class="number">{{ army.amount }}</span>
                                                </div>
                                            </li>
                                        {% endfor %}

                                    </ul>
                                    <div class="clear"></div>
                                </div>
                            </div>
                        </div>
                    </td>
                {% endfor %}
            </tr>
            </tbody>
        </table>
    {% endif %}
</div>




{# WHEN MOVING
<td>
									<div class="blocks_top">
										<h3 class="h3c">
											<p class="gmove">
												<a href="/map?g=1521641">symfony</a>
											</p>
										</h3>
										<div class="blocks_bg">
											<div class="blocks_bottom">
												<div class="p">
												
													Se déplace entre <a href="/map?c=794410">Les Toromos-les-Guibain</a> et <a href="/map?c=794450">Annomoi</a>
													<div>
													
	<script type="text/javascript">
	mt.js.Timer.TIMES="jhms";
	mt.js.Timer.alloc('2021-11-06 12:18:36','2021-11-06 13:23:27',2,null);
	</script><div id="timer_0" class="timer">1h 03m </div>

													</div>
												
												</div>
												<p>
													
	<img src="/img/help.gif" class="help" onmouseover="mt.js.Tip.show(this,'<div class=\'tiptop\'><div class=\'tipbottom\'><div class=\'tipbg\'><h1>Réputation</h1>La réputation de votre général grandit quand il remporte des batailles. Chaque point de réputation permet à votre général de réduire le coût en or des unités qui l\'accompagnent.</div></div></div>')" onmouseout="mt.js.Tip.hide()">

													<span class="dt">Réputation</span> :
													
	<strong>1</strong> <img src="/img/icons/l_rep.png">

												</p>
												<p>
													
	<img src="/img/help.gif" class="help" onmouseover="mt.js.Tip.show(this,'<div class=\'tiptop\'><div class=\'tipbottom\'><div class=\'tipbg\'><h1>Entretien</h1>Le coût d\'entretien des soldats à chaque tour.</div></div></div>')" onmouseout="mt.js.Tip.hide()">

													<span class="dt">Entretien</span> :
													
	<strong>1</strong> <img src="/img/icons/small/res_gold.gif">

												</p>
											
	<ul class="ismall">
		
		<li>
	<div class="" onmouseover="mt.js.Tip.show(this,'<div class=\'tiptop\'><div class=\'tipbottom\'><div class=\'tipbg\'><h1>Soldat</h1>Un bon soldat qui fera bien son travail tant qu\'il sera payé.</div></div></div>')" onmouseout="mt.js.Tip.hide()">
		<img src="/img/icons/small/unit_sold.gif" alt="">
		<span class="number">1</span>
	</div>
</li>
		
<li>
	<div class="" onmouseover="mt.js.Tip.show(this,'<div class=\'tiptop\'><div class=\'tipbottom\'><div class=\'tipbg\'><h1>Catapulte</h1>Une catapulte est une unité ayant un bonus de +200% mais uniquement lors de l\'attaque d\'une ville ou d\'un lieu.</div></div></div>')" onmouseout="mt.js.Tip.hide()">
		<img src="/img/icons/small/unit_cat.gif" alt="">
		<span class="number">1</span>
	</div>
</li>
		
	</ul>
	<div class="clear"></div>
	

											</div>
										</div>
									</div>
								</td>
#}

EternalKingdom/templates/Management/Components/KingdomTab.html.twig
<div id="kingdom" style="display: none;">
    {% if (lord.kingdom|length) == 0 %}
        <p class="nothing">
            {{ 'tabs.kingdom.noTown' | trans([], 'Management') }}
        </p>
    {% else %}
        <div class="tablevb_top">
            <div class="tablevb_bottom">
                <div class="tablevb_bg">
                    <table class="tablevb">
                        <tbody>

                            {# Column names #}
                            <tr class="first">
                                <th> {{ 'tabs.kingdom.town' | trans([], 'Management') }} </th>
                                <th> {{ 'tabs.kingdom.status' | trans([], 'Management') }} </th>
                                <th>
                                    <span
                                        onmouseover="mt.js.Tip.show(this,'&lt;div class=\'tiptop\'&gt;&lt;div class=\'tipbottom\'&gt;&lt;div class=\'tipbg\'&gt;&lt;h1&gt;{{ 'stats.trade.name' | trans([], 'Management') }}&lt;/h1&gt;{{ 'stats.trade.desc' | trans([], 'Management') }}&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;')"
                                        onmouseout="mt.js.Tip.hide()">
                                        <img src="{{ asset('img/icons/l_tax.png') }}">
                                    </span>
                                </th>
                                <th>
                                    <span
                                        onmouseover="mt.js.Tip.show(this,'&lt;div class=\'tiptop\'&gt;&lt;div class=\'tipbottom\'&gt;&lt;div class=\'tipbg\'&gt;&lt;h1&gt;{{ 'tabs.generals.maintenance' | trans([], 'Management') }}&lt;/h1&gt;{{ 'tabs.generals.maintenanceTooltip' | trans([], 'Management') }}&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;')"
                                        onmouseout="mt.js.Tip.hide()">
                                        <strong></strong> 
                                        <img src="{{ asset('img/icons/Small/res_gold.gif') }}">
                                    </span>
                                </th>
                                <th>
                                    <span
                                        onmouseover="mt.js.Tip.show(this,'&lt;div class=\'tiptop\'&gt;&lt;div class=\'tipbottom\'&gt;&lt;div class=\'tipbg\'&gt;&lt;h1&gt;{{ 'tabs.kingdom.units' | trans([], 'Management') }}&lt;/h1&gt;{{ 'tabs.kingdom.unitsTooltip' | trans([], 'Management') }}&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;')"
                                        onmouseout="mt.js.Tip.hide()">
                                        <img src="{{ asset('img/icons/l_battle.png') }}">
                                    </span>
                                </th>
                            </tr>

                            {% set a = 0 %}
                            {% for town in lord.kingdom %}
                                {% set status = '' %}
                                {% set trade = town.trade %}
                                {% set freeSoldiers = 0 %}
                                
                                {% if town == lord.city.cityNode %}
                                    {% set status = 'Votre Capitale' %}
                                    {% set trade = '--' %}
                                    {% set freeSoldiers = [0,5,10,20,50,100][lord.city.buildingLevel('barracks')] %}
                                    {% set tradeTooltip = ('tabs.kingdom.noCityTrade' | trans([], 'Management')) %}
                                {% endif %}

                                {% if town == lord.city.cityNode %}        {# CHECK IF ITS A CITYNODE #}
                                    {% set tradeTooltip = ('tabs.kingdom.noCityTrade' | trans([], 'Management')) %}
                                {% elseif town.armyContainer.TotalUnitCount > town.trade/2 %}
                                    {% set iconURL = asset('img/icons/c_up.png') %}
                                    {% set tradeTooltip = ('tabs.kingdom.increasingTrade' | trans([], 'Management')) %}
                                {% elseif town.armyContainer.TotalUnitCount == town.trade//2 %}
                                    {% set iconURL = asset('img/icons/c_equal.png') %}
                                    {% set tradeTooltip = ('tabs.kingdom.stableTrade' | trans([], 'Management')) %}
                                {% elseif town.armyContainer.TotalUnitCount < town.trade/2 %}
                                    {% set iconURL = asset('img/icons/c_down.png') %}
                                    {% set tradeTooltip = ('tabs.kingdom.decreasingTrade' | trans([], 'Management')) %}
                                {% endif %}
                                
                                <tr {% if a%2 == 0 %} class="even" {% endif %}>
                                    <td>
                                        <a href="/map?id={{ app.request.get('id') }}">{{ town.name }}</a>
                                    </td>
                                    <td>
                                        {{ status }}
                                    </td>
                                    <td class="center">
                                        <span {% if trade!='--' and trade<0 %}class="need"{% endif %}
                                            onmouseover="mt.js.Tip.show(this,'&lt;div class=\'tiptop\'&gt;&lt;div class=\'tipbottom\'&gt;&lt;div class=\'tipbg\'&gt;{{ tradeTooltip }}&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;')"
                                            onmouseout="mt.js.Tip.hide()">{{ trade }}      
                                            {% if town != lord.city.cityNode %}        {# CHECK IF ITS A CITYNODE #}
                                                <img src="{{ iconURL }}">
                                            {% endif %}     
                                        </span>
                                    </td>
                                    <td class="center">{{ town.armyContainer.TotalUnitCount - freeSoldiers }}</td>
                                    <td class="{% if town.armyContainer.TotalUnitCount == 0 %}need{% endif %} center"
                                        {% if town.armyContainer.TotalUnitCount == 0 %}
                                            onmouseover="mt.js.Tip.show(this,'<div class=\'tiptop\'><div class=\'tipbottom\'><div class=\'tipbg\'>Aucune unité en défense</div></div></div>')"
                                        {% else %}
                                            onmouseover="mt.js.Tip.show(this,'&lt;div class=\'tiptop\'&gt;&lt;div class=\'tipbottom\'&gt;&lt;div class=\'tipbg\'&gt;&lt;h1&gt;{{ 'tabs.kingdom.defense' | trans([], 'Management') }}&lt;/h1&gt;		&lt;ul class=&quot;ismall&quot;&gt;				{% for army in town.armyContainer.unitArmies %}&lt;li&gt;	&lt;div class=&quot;&quot; onmouseover=&quot;mt.js.Tip.show(this,\'&amp;lt;div class=\\\'tiptop\\\'&amp;gt;&amp;lt;div class=\\\'tipbottom\\\'&amp;gt;&amp;lt;div class=\\\'tipbg\\\'&amp;gt;&amp;lt;h1&amp;gt;{{ army.resource.name }}&amp;lt;/h1&amp;gt;{{ ('units.'~army.resource.name~'.desc') | trans([], 'Management') }}&amp;lt;/div&amp;gt;&amp;lt;/div&amp;gt;&amp;lt;/div&amp;gt;\')&quot; onmouseout=&quot;mt.js.Tip.hide()&quot;&gt;		&lt;img src=&quot;{{ asset('img/icons/small/u_'~army.resource.name~'.gif') }}&quot; alt=&quot;&quot;/&gt;		&lt;span class=&quot;number&quot;&gt;{{ army.amount }}&lt;/span&gt;	&lt;/div&gt;&lt;/li&gt; {% endfor %}       &lt;/ul&gt;	&lt;div class=&quot;clear&quot;&gt;&lt;/div&gt;	&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;')"
                                        {% endif %}
                                        onmouseout="mt.js.Tip.hide()">
                                        {{ town.armyContainer.TotalUnitCount }}
                                    </td> 
                                </tr>
                                {% set a = a+1 %}
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    {% endif %}
</div>

{# IF RESOURCE ON THE NODE
<td>
    Champ de Lin
	<div class="sres">
		<img src="/img/icons/small/res_lin.gif" alt="">
		<span class="number">50</span>
	</div>
</td>
#}

EternalKingdom/templates/Management/Components/LordInfo.html.twig
{% trans_default_domain 'Management' %}

<ul>
	<li>
	    <img src="{{ asset('img/help.gif') }}" class="help" onmouseover="mt.js.Tip.show(this,'<div class=\'tiptop\'><div class=\'tipbottom\'><div class=\'tipbg\'><h1>{{ 'stats.title.name' | trans([], 'Management') }}</h1>{{ 'stats.title.desc' | trans([], 'Management') }}</div></div></div>')" onmouseout="mt.js.Tip.hide()">
        <span class="dt">{{ 'stats.title.name' | trans }} :</span>
		<b>{{ ('lord.titles.'~lord.title) | trans([], 'Common') }}</b>
	</li>

	<li>
		<img src="{{ asset('img/help.gif') }}" class="help" onmouseover="mt.js.Tip.show(this,'<div class=\'tiptop\'><div class=\'tipbottom\'><div class=\'tipbg\'><h1>{{ ('stats.age.name') | trans }}</h1>{{ ('stats.age.name') | trans }}</div></div></div>')" onmouseout="mt.js.Tip.hide()">
        <span class="dt">{{ ('stats.age.name') | trans }} :</span>
		<b>{{ 'lord.age' | trans({'%years%': lord.ageYear, '%months%': lord.ageMonth|number_format }, "Common") }}</b>
	</li>
	
    <li>
	<img src="{{ asset('img/help.gif') }}" class="help" onmouseover="mt.js.Tip.show(this,'<div class=\'tiptop\'><div class=\'tipbottom\'><div class=\'tipbg\'><h1>{{ 'stats.health.name' | trans }}</h1>{{ 'stats.health.desc' | trans }}</div></div></div>')" onmouseout="mt.js.Tip.hide()">
    <span class="dt">{{ 'stats.health.name' | trans }} :</span>
	<b>{{ ('healths.'~lord.health) | trans }}</b>
	</li>
	
    <li>
	    <img src="{{ asset('img/help.gif') }}" class="help" onmouseover="mt.js.Tip.show(this,'<div class=\'tiptop\'><div class=\'tipbottom\'><div class=\'tipbg\'><h1>{{ 'stats.glory.name' | trans }}</h1>{{ 'stats.glory.desc' | trans }}</div></div></div>')" onmouseout="mt.js.Tip.hide()">
        <span class="dt">{{ 'stats.glory.name' | trans }} :</span>
	    <b><strong>{{ lord.glory }}</strong> <img src="{{ asset('img/icons/l_up.png') }}"></b>
	</li>
	
    <li>
		<img src="{{ asset('img/help.gif') }}" class="help" onmouseover="mt.js.Tip.show(this,'<div class=\'tiptop\'><div class=\'tipbottom\'><div class=\'tipbg\'><h1>{{ 'stats.maxGlory.name' | trans }}</h1>{{ 'stats.maxGlory.desc' | trans }}</div></div></div>')" onmouseout="mt.js.Tip.hide()">
        <span class="dt">{{ 'stats.maxGlory.name' | trans }} :</span>
		<b><strong>{{ lord.maxGlory }}</strong> <img src="{{ asset('img/icons/l_up.png') }}"></b>
	</li>
										
    <li>
	    <img src="{{ asset('img/help.gif') }}" class="help" onmouseover="mt.js.Tip.show(this,'<div class=\'tiptop\'><div class=\'tipbottom\'><div class=\'tipbg\'><h1>{{ 'stats.trade.name' | trans }}</h1>{{ 'stats.trade.desc' | trans }}</div></div></div>')" onmouseout="mt.js.Tip.hide()">
        <span class="dt">{{ 'stats.trade.name' | trans }} :</span>
		<b><strong>{{ lord.trade }}</strong> <img src="{{ asset('img/icons/small/res_gold.gif') }}"></b>
	</li>
</ul>

EternalKingdom/templates/Management/Components/VassalsTab.html.twig
<div id="vassals" style="">
    <p class="nothing">
        {# TODO : IMPLEMENT VASSALS AND TEST THEM #}
        {{ 'tabs.vassals.noVassal' | trans([], 'Management') }}
    </p>
    <table class="blocks">
        <tbody>
        <tr>
            {# TODO IMPLEMENT VASSALS
            {% for vassal in lord.vassals %}
                <td>
                    <div class="blocks_top">
                        <h3 class="h3c">
                            <a href="">{{ vassal.name }}</a>  
                        </h3>
                        <div class="blocks_bg">
                            <div class="blocks_bottom">
                                <p><span class="dt">{{ stats.title.name | trans([], 'Management') }}</span> : {{ vassal.title | trans([], 'Management') }}</p>
                                <p>
                                    <span class="dt">{{ stats.glory.name | trans([], 'Management') }}</span> : <strong>{{ vassal.glory }}</strong> 
                                    <img src="{{ asset('img/icons/l_up.png') }}">
                                </p>
                                <p>
                                    <span class="dt">{{ tabs.vassals.taxes | trans([], 'Management') }}</span> : <strong>2</strong>  TODO DETECT TAXES
                                    <img src="{{ asset('img/icons/Small/res_gold.gif') }}">
                                    (20%)
                                </p>
                                <p>
                                    <span class="dt">{{ tabs.vassals.taxesToCollect | trans([], 'Management') }}</span> : <strong>27</strong>  TODO DETECT TAXES
                                    <img src="{{ asset('img/icons/Small/res_gold.gif') }}">
                                    <a href="*">{{ tabs.vassals.collect | trans([], 'Management') }}</a> TODO IMPLEMENT ROUTE REQUEST 
                                </p>

                            </div>
                        </div>
                    </div>
                </td>
            {% endfor %}
            #}
        </tr>
        </tbody>
    </table>
</div>