EternalKingdom/src/Entity/ArmyContainer.php
<?php

namespace App\Entity;

use App\Repository\ArmyContainerRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ArmyContainerRepository::class)
 */
class ArmyContainer
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToMany(targetEntity=UnitArmy::class, mappedBy="container", cascade={"persist", "remove"}, orphanRemoval=true)
     */
    private $unitArmies;

    public function __construct()
    {
        $this->unitArmies = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection|UnitArmy[]
     */
    public function getUnitArmies(): Collection
    {
        return $this->unitArmies;
    }

    public function addUnitArmy(UnitArmy $army): self
    {
        if (!$this->unitArmies->contains($army)) {
            $this->unitArmies[] = $army;
            $army->setContainer($this);
        }

        return $this;
    }

    public function removeUnitArmy(UnitArmy $army): self
    {
        if ($this->unitArmies->removeElement($army)) {
            // set the owning side to null (unless already changed)
            if ($army->getContainer() === $this) {
                $army->setContainer(null);
            }
        }

        return $this;
    }

    public function getUnitCount(String $unitName): int
    {
        foreach($this->unitArmies as $army) 
        {
            if($army->getResource()->getName() !== $unitName) continue;
            return $army->getAmount();
        }
        return 0;
    }

    public function getTotalUnitCount(): int
    {
        $total = 0;
        foreach($this->unitArmies as $army)
        {
            $total += $army->getAmount();
        }
        return $total;
    }
}

EternalKingdom/src/Entity/City.php
<?php

namespace App\Entity;

use App\Entity\World\CityNode;
use App\Repository\CityRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CityRepository::class)
 */
class City
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\OneToOne(targetEntity=Lord::class, inversedBy="city", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $lord;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $grid = '';

    /**
     * @ORM\Column(type="smallint")
     */
    private $remainingTurns = 100;

    /**
     * @ORM\Column(type="smallint")
     */
    private $wastedTurns = 0;

    /**
     * @ORM\OneToMany(targetEntity=Storage::class, mappedBy="city", cascade={"persist", "remove"}, orphanRemoval=true)
     */
    private $storages;

    /**
     * @ORM\OneToMany(targetEntity=BuiltBuildings::class, mappedBy="city", cascade={"persist", "remove"}, orphanRemoval=true)
     */
    private $builtBuildings;

    /**
     * @ORM\Column(type="boolean")
     */
    private $recruiting = true;

    /**
     * @ORM\ManyToOne(targetEntity=Constructions::class)
     */
    private $constructionProject;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $projectLevel;

    /**
     * @ORM\OneToOne(targetEntity=CityNode::class, mappedBy="city", cascade={"persist", "remove"})
     */
    private $cityNode;

    public function __construct()
    {
        $this->storages = new ArrayCollection();
        $this->builtBuildings = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getLord(): ?Lord
    {
        return $this->lord;
    }

    public function setLord(Lord $lord): self
    {
        $this->lord = $lord;
        $lord->addTerritory($this->cityNode);

        return $this;
    }

    public function getGrid(): ?string
    {
        return $this->grid;
    }

    public function setGrid(string $grid): self
    {
        $this->grid = $grid;

        return $this;
    }

    public function getRemainingTurns(): ?int
    {
        return $this->remainingTurns;
    }

    public function setRemainingTurns(int $remainingTurns): self
    {
        $this->remainingTurns = $remainingTurns;

        return $this;
    }

    public function getWastedTurns(): ?int
    {
        return $this->wastedTurns;
    }

    public function setWastedTurns(int $wastedTurns): self
    {
        $this->wastedTurns = $wastedTurns;

        return $this;
    }

    /**
     * @return Collection|Storage[]
     */
    public function getStorages(): Collection
    {
        return $this->storages;
    }

    public function addStorage(Storage $storage): self
    {
        if (!$this->storages->contains($storage)) {
            $this->storages[] = $storage;
            $storage->setCity($this);
        }

        return $this;
    }

    public function removeStorage(Storage $storage): self
    {
        if ($this->storages->removeElement($storage)) {
            // set the owning side to null (unless already changed)
            if ($storage->getCity() === $this) {
                $storage->setCity(null);
            }
        }

        return $this;
    }

    public function getStorageCount(string $resourceName) : int //TODO : Maybe optimize ?
    {
        foreach($this->storages as $storage) 
        {
            if($storage->getResource()->getName() !== $resourceName) continue;
            return $storage->getAmount();
        }
        return 0;
    }

    public function getPopulationCount() : int
    {
        $count = 0;
        foreach($this->storages as $storage) 
        {
            if($storage->getResource()->getResourceType() !== 'population') continue;
            $count += $storage->getAmount();
        }
        return $count;
    }

    public function getUnitCount(string $resourceName) : int
    {
        $count = $this->cityNode->getArmyContainer()->getUnitCount($resourceName);
        return $count;
    }

    /**
     * @return Collection|BuiltBuildings[]
     */
    public function getBuiltBuildings(): Collection
    {
        return $this->builtBuildings;
    }

    public function addBuiltBuilding(BuiltBuildings $builtBuilding): self
    {
        if (!$this->builtBuildings->contains($builtBuilding)) {
            $this->builtBuildings[] = $builtBuilding;
            $builtBuilding->setCity($this);
        }

        return $this;
    }

    public function removeBuiltBuilding(BuiltBuildings $builtBuilding): self
    {
        if ($this->builtBuildings->removeElement($builtBuilding)) {
            // set the owning side to null (unless already changed)
            if ($builtBuilding->getCity() === $this) {
                $builtBuilding->setCity(null);
            }
        }

        return $this;
    }

    public function getBuildingLevel(string $buildingName)
    {
        foreach($this->builtBuildings as $builtBuilding) 
        {
            if($builtBuilding->getBuilding()->getName() !== $buildingName) continue;
            return $builtBuilding->getLevel();
        }
        return 0;
    }

    public function isRecruiting(): ?bool
    {
        return $this->recruiting;
    }

    public function setRecruiting(bool $recruiting): self
    {
        $this->recruiting = $recruiting;

        return $this;
    }

    public function getConstructionProject(): ?Constructions
    {
        return $this->constructionProject;
    }

    public function setConstructionProject(?Constructions $constructionProject): self
    {
        $this->constructionProject = $constructionProject;

        return $this;
    }

    public function getProjectLevel(): ?int
    {
        return $this->projectLevel;
    }

    public function setProjectLevel(?int $projectLevel): self
    {
        $this->projectLevel = $projectLevel;

        return $this;
    }

    public function getCityNode(): ?CityNode
    {
        return $this->cityNode;
    }

    public function setCityNode(CityNode $cityNode): self
    {
        // set the owning side of the relation if necessary
        if ($cityNode->getCity() !== $this) {
            $cityNode->setCity($this);
        }

        $this->cityNode = $cityNode;

        return $this;
    }
   

}

EternalKingdom/templates/City/city.html.twig
{# Templates/City/optionUpgradeSoldier.html.twig #}
{# City skeleton (It displays army, city options, resource stocks, grid and logs) #}

{% extends 'base.html.twig' %}

{% trans_default_domain 'City' %}

{% block title %}
    - {{ 'tabHeader' | trans }}
{% endblock %}

{% block stylesheets %}
{% endblock %}

{% block javascripts %}
    <script type="text/javascript" src="{{ asset('js/utility.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/gameGrid.js') }}" xmlns="http://www.w3.org/1999/html"></script>
{% endblock %}

{% block content %}
    <p class = "ServerData" data-grid="{{ lord.city.grid }}" {% if lord.city.constructionProject != null %}data-has-construction="true"{% endif %}></p>
    <ul class="resources rescity">
        {% for resourceName in ['wheat', 'gold', 'wood', 'iron', 'lin', 'horse'] %}
            {% set maxAmount = maxAmounts[resourceName] %}
            <li>
                <div
                        class="res"
                        onmouseover="mt.js.Tip.show(this,'<div class=\'tiptop\'><div class=\'tipbottom\'><div class=\'tipbg\'><h1>{{ ('resources.'~resourceName~'.name') | trans }}</h1><div class=\'infos max\'>max : {{ maxAmount }}</div>{{ ('resources.'~resourceName~'.desc') | trans }}</div></div></div>')"
                        onmouseout="mt.js.Tip.hide()"
                >
                    <div class="resp">
                        <span class="n" data-max="{{ maxAmount }}">{{ lord.city.storageCount(resourceName) }}</span>
                    </div>
                    <img src="{{ asset('img/icons/res_'~resourceName~'.png') }}" alt="" class="" />
                </div>
            </li>
        {% endfor %}
    </ul>

    <h1 class="city">{{ lord.city.name }}</h1>
    <div class="h1">
        <div class="h1mid">
            <div class="h1bottom">
                <table class="city">
                    <tbody>
                    <tr>
                        <td>
                            <!-- UNITS -->
                            <div class="box1 unitsgar">
                                <div class="box1bottom">
                                    <div class="box1bg">
                                        {# At least display the soldier #}
                                        {% set unitsToDisplay = ['soldier'] %}
                                        {% set unitsCount = lord.city.cityNode.armyContainer.totalUnitCount %}
                                        {% if unitsCount > 0 and unitsCount != lord.city.cityNode.armyContainer.unitCount('soldier') %}
                                            {% set unitsToDisplay = ['soldier', 'pikeman', 'archer', 'horseman', 'knight', 'mountedArcher', 'paladin', 'catapult', 'ballista'] %}
                                        {% endif %}
                                        <h2 class="h2a" data-armycount="{{ unitsCount }}">{{ 'header.units' | trans }}</h2>
                                            <ul class = "army items">
                                                {% for unit in unitsToDisplay %}
                                                    {% set unitCount = lord.city.cityNode.armyContainer.unitCount(unit) %}
                                                    <li>
                                                        <div class="item{% if unitCount==0 %} disable{% endif %}"
                                                            onmouseover="mt.js.Tip.show(this,'<div class=\'tiptop\'><div class=\'tipbottom\'><div class=\'tipbg\'><h1>{{ ('units.'~unit~'.name') | trans([], "Common") }}</h1>{{ ('units.'~unit~'.desc') | trans([], "Common") }}</div></div></div>')"
                                                            onmouseout="mt.js.Tip.hide()">
                                                            <img src="/img/icons/u_{{ unit }}.png" alt="{{ unit }} icon">
                                                            <span class="number">{{ unitCount }}</span>
                                                        </div>
                                                    </li>
                                                {% endfor %}
                                            </ul>

                                        <p id="noArmyMessage" class="nothing{% if unitsCount > 0 %} hidden{% endif %}">
                                            {{ 'messages.noArmy' | trans }}
                                        </p>
                                            
                                        <div class="clear"></div>
                                    </div>
                                </div>
                            </div>

                            <!-- OPTIONS -->
                            <div class="box1">
                                <div class="box1bottom">
                                    <div class="box1bg">
                                        <h2 class="h2d">{% block cityOptionsTitle %}{% endblock %}</h2>
                                        {% block cityOption %}
                                        {% endblock %}
                                    </div>
                                </div>
                            </div>

                            <!-- BUILDINGS -->
                            <div class="box1">
                                <div class="box1bottom">
                                    <div class="box1bg">
                                        <h2 class="h2d">{{ 'header.buildings' | trans }}</h2>
                                        <ul class="listbuildings">
                                            {% if lord.city.builtBuildings|length > 0 %}
                                                {% for builtBuilding in lord.city.builtBuildings %}
                                                    {% include 'City/Components/building.html.twig' with {'builtBuilding': builtBuilding} %}
                                                {% endfor %}
                                            {% else %}
                                                <div class="clear"></div>
                                                <p class="nothing">
                                                    {{ 'messages.noWorker' | trans }}
                                                </p>
                                            {% endif %}
                                        </ul>
                                        <div class="clear"></div>
                                    </div>
                                </div>
                            </div>
                        </td>

                        <td class="right">
                            <div class="box2">
                                <div class="box2bottom">
                                    <div class="box2bg">
                                        <h2 class="h2e cut" data-populationcount="{{ lord.city.populationCount }}">{{ 'header.population' | trans }}</h2>
                                        <ul class="population items">
                                            {% for jobName in ['farmer', 'lumberjack', 'worker', 'merchant', 'recruiter', 'citizen'] %}
                                                <li>
                                                <div
                                                        class="item {% if lord.city.storageCount(jobName)==0 %} disable {% endif %}"
                                                        onmouseover="mt.js.Tip.show(this,'<div class=\'tiptop\'><div class=\'tipbottom\'><div class=\'tipbg\'><h1>{{ ('jobs.'~jobName~'.name') | trans }}</h1>{{ ('jobs.'~jobName~'.desc') | trans }}</div></div></div>')"
                                                        onmouseout="mt.js.Tip.hide()"
                                                >
                                                    <img src="{{ asset('img/icons/people_'~jobName~'.gif') }}" alt="" />
                                                    <span class="number">{{ lord.city.storageCount(jobName) }}</span>
                                                </div>
                                                </li>
                                            {% endfor %}
                                        </ul>
                                        <div class="clear"></div>
                                    </div>
                                </div>
                            </div>

                            <div>
                                <div class="puzzle">
                                    <div class="infos" id="turns">
                                                                        <span
                                                                                id="counter"
                                                                                onmouseover="mt.js.Tip.show(this,'<div class=\'tiptop\'><div class=\'tipbottom\'><div class=\'tipbg\'>{{ 'messages.wastedTurns' | trans }}<b>1/21</b></div></div></div>')"
                                                                                onmouseout="mt.js.Tip.hide()"
                                                                        >
                                                                            {{ lord.city.remainingTurns }}
                                                                        </span>
                                        {{ 'messages.remainingTurns' | trans }} :
                                    </div>
                                    <div id="puzzleframe">
                                        <canvas id="puzzleCanvas"></canvas>
                                        <canvas id="frontCanvas"></canvas>
                                        <a class="puzzleturns disable">
                                            Oh ben c'est con t'as<br>
                                            plus de <img src="{{ asset('img/icons/small/res_rec.gif') }}" alt="Turn icon"> <b>tours</b> !
                                        </a>
                                    </div>
                                    <div id="snackbar">{{ 'messages.forbiddenSwap' | trans }}</div>
                                </div>
                            </div>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        // mt.js.Tip.exclude("puzzle");
    </script>

    <div class="log">
        <h3>{{ 'header.logs' | trans }}</h3>
        <div class="teml">
            <ul>
                {% include 'City/Components/LogsList.html.twig' with
                    { 'logs': logs }
                %}
            </ul>
        </div>
    </div>
{% endblock %}

EternalKingdom/templates/City/index.html.twig
{# Templates/City/optionUpgradeSoldier.html.twig #}
{# City index (no options has been selected - lighter to load since it doesn't to compute any options data) #}

{% extends 'City/city.html.twig' %}

{% trans_default_domain 'City' %}

{% block cityOptionsTitle %}
	{{ 'header.actions' | trans }}
{% endblock %}

{% block cityOption %}
	<div class="contactions">
		{% include 'City/Components/pendingConstruction.html.twig' with
			{'constructionProject': lord.city.constructionProject, 'remainingHammers': lord.city.storageCount('remainingHammers')}
		%}

		{% set actionAvailable = false %}
		<ul class="actions">
			{% if lord.city.getStorageCount('worker') > 0 %}
				<li>
					{% set spanName = ('messages.build.start' | trans) %}
					{% set actionAvailable = true %}
					{% if lord.city.constructionProject != null %}
						{% set spanName = ('messages.build.list' | trans) %}
					{% endif %}
					<div onclick="document.location = '/city/chooseConstruction'">
						<img src="{{ asset('img/icons/a_build.png') }}" alt="Build Action">
						<span>{{ spanName }}</span>
					</div>
				</li>
			{% endif %}
			{% if lord.city.constructionProject != null %}
				{% set actionAvailable = true %}
				<li>
					<div onclick="document.location = '/city/cancelConstruction'">
						<img src="{{ asset('img/icons/a_nobuild.png') }}" alt="Cancel Construction Action">
						<span>{{ 'messages.build.cancel' | trans }}</span>
					</div>
				</li>
			{% endif %}
			{% if lord.city.buildingLevel('barracks') > 0 %}
				{% set actionAvailable = true %}
				<li>
					<div onclick="document.location = '/city/chooseSoldierUpgrade'">
						<img src="{{ asset('/img/icons/a_sold.png') }}" alt="Upgrade Units Action">
						<span>{{ 'header.soldierOptions' | trans }}</span>
					</div>
				</li>
				{% endif %}
			{% if lord.city.buildingLevel('cauldron') > 0 or lord.city.buildingLevel('butcher') > 0 or lord.city.buildingLevel('factory') > 0 %}
				{% set actionAvailable = true %}
				<li>
					<div onclick="document.location = '/city/chooseResourceConversion'">
						<img src="{{ asset('/img/icons/a_resconvert.png') }}" alt="Convert Resources Action">
						<span>{{ 'header.convertResources' | trans }}</span>
					</div>
				</li>
			{% endif %}
			{% set generalCount = lord.generals|length %}
			{% if lord.city.buildingLevel('headquarters') > 0 and generalCount < lord.city.buildingLevel('headquarters') %}
				{% set actionAvailable = true %}
				<li onmouseover="mt.js.Tip.show(this,'<div class=\'tiptop\'><div class=\'tipbottom\'><div class=\'tipbg\'><h1>{{ 'header.recruitGeneral' | trans }}</h1>{{ 'messages.recruitGeneral.desc' | trans }}<strong>{{ 50 * 2**generalCount }}</strong> <img src=\'{{ asset('img/icons/small/res_gold.gif') }}\'/>.</div></div></div>')"
					onmouseout="mt.js.Tip.hide()"
				>
					<div onclick="document.location = '/city/chooseGeneralName';">
						<img src="{{ asset('/img/icons/a_gen.png') }}" alt="Recruit General Action">
						<span>{{ 'header.recruitGeneral' | trans }}</span>
					</div>
				</li>
			{% endif %}
		</ul>
		{% if actionAvailable == false %}
			<p class="nothing">
				{{ 'messages.noAction' | trans }}
			</p>
		{% endif %}
		<div class="clear">
		</div>
	</div>
{% endblock %}

EternalKingdom/templates/City/optionChooseBuilding.html.twig
{# Templates/City/optionChooseBuilding.html.twig #}
{# City option which permits to start a building project #}

{% extends 'City/city.html.twig' %}
{% trans_default_domain 'City' %}

{% block cityOptionsTitle %}
	{{ 'header.build' | trans([], 'City') }}
{% endblock %}

{% block cityOption %}

	{% include 'City/Components/pendingConstruction.html.twig' with
		{'constructionProject': lord.city.constructionProject, 'remainingHammers': lord.city.storageCount('remainingHammers')}
	%}
	{# Necessary since we added a feedback to know the current construction (the building list had a margin-top of -15px in its CSS) #}
	{% if lord.city.constructionProject %}
		<div style="margin-bottom: 6px"></div>
	{% else %}
		<div style="margin-bottom: -15px"></div>
	{% endif %}
<ul class="buildings">
	{% for buildingProject in constructionProjects %}
		{% include 'City/Components/buildingProject.html.twig' with {'buildingProject': buildingProject} %}
	{% endfor %}
</ul>
<div class="clear"></div>
<a href="{{ path('app_city_city') }}" class="button">{{ 'messages.back' | trans([], 'City') }}</a>
{% endblock %}

EternalKingdom/templates/City/optionConvertResources.html.twig
{# Templates/City/optionConvertRessources.html.twig #}
{# City option which permits to convertResources to other ones #}

{% extends 'City/city.html.twig' %}

{% block cityOptionsTitle %}
	{{ 'header.convertResources' | trans([], 'City') }}
{% endblock %}

{% block cityOption %}
<table class="blocks2">
	<tbody>
	<tr>
	{% set a = 0 %}
		{% for resourceSchemas in conversionSchemas %}
			{% if a%2 == 0 %}
				</tr> <tr>
			{% endif %}
			{% include 'City/Components/convertResources.html.twig' with {'resourceSchemas': resourceSchemas} %}
			{% set a = a+1 %}
		{% endfor %}	
	</tr>
	</tbody>
</table>
<a href="{{ path('app_city_city') }}" class="button">{{ 'messages.back' | trans([], 'City') }}</a>
{% endblock %}

EternalKingdom/templates/City/optionRecruitGeneral.html.twig
{% extends 'City/city.html.twig' %}

{% block cityOptionsTitle %}
	{{ 'header.recruitGeneral' | trans([], 'City') }}
{% endblock %}

{% block cityOption %}
	<div class="centeredDiv">
		<p class="firstp">
			Merci de donner un nom à votre général :
		</p>

		<form action="{{ path('app_city_recruitgeneral') }}" method="POST">
			<p>Nom : <input name="name" maxlength="20" class="inputtext"> <input type="submit" value="Valider" class="button"></p>
		</form>
	</div>
	<a href="{{ path('app_city_city') }}" class="button">{{ 'messages.back' | trans([], 'City') }}</a>
{% endblock %}

EternalKingdom/templates/City/optionUpgradeSoldier.html.twig
{# Templates/City/optionUpgradeSoldier.html.twig #}
{# City option which permits to upgrade soldier to specialized units #}

{% extends 'City/city.html.twig' %}

{% block cityOptionsTitle %}
    {{ 'header.soldierOptions' | trans([], 'City') }}
{% endblock %}

{% block cityOption %}

    {# TODO Refactor this, backend has changed! #}
    {# TODO Make a component per unit conversion (with building required, unit to convert, resource required, ... #}

    {% set canUpgradeSoldier = false %}
    {% for resourceSchemas in upgradeSchemas %}
        {% for schema in resourceSchemas[1:] %}
            {% if lord.city.buildingLevel(schema.requiredBuilding.name) > 0 %}
                {% set canUpgradeSoldier = true %}
            {% endif %}
        {% endfor %}
    {% endfor %}

    {% if not canUpgradeSoldier %}
        <p class="firstp nothing">
            {{ 'messages.soldierOptions.noRequiredBuilding' | trans([], 'City') }}
        </p>
    {% else %}
        <table class="blocks2">
            <tbody>
            <tr>
                {% set a = 0 %}
                {% for resourceSchemas in upgradeSchemas %}
                    {% if a%2 == 0 %}
                        </tr><tr>
                    {% endif %}
                    {% include 'City/Components/upgradeSoldier.html.twig' with {'resourceSchemas': resourceSchemas} %}
                    {% set a = a+1 %}
                {% endfor %}
            </tr>
            </tbody>
        </table>
    {% endif %}

    {% if lord.city.recruiting %}
        {% set buttonText =  'messages.soldierOptions.recruitment.disable' | trans([], 'City')%}
    {% else %}
        {% set buttonText =  'messages.soldierOptions.recruitment.enable' | trans([], 'City')%}
    {% endif %}

    <div class="butimpro">
        <div class="float">
            <a href="{{ path('app_city_togglerecruitment') }}" class="button twolines float"
               onmouseover="mt.js.Tip.show(this,'<div class=\'tiptop\'><div class=\'tipbottom\'><div class=\'tipbg\'>{{ 'messages.soldierOptions.recruitment.desc' | trans([], 'City') }}</div></div></div>')"
               onmouseout="mt.js.Tip.hide()">{{ buttonText }}</a>
        </div>

        <div class="float">
            <a href="{{ path('app_city_city') }}" class="button float">{{ 'messages.back' | trans([], 'City') }}</a>
        </div>
    </div>

    <div class="clear">
    </div>
{% endblock %}